Bhuma_Devi_Acharya_Dot_Net_Assignment/Bhuma_Devi_Acharya_Dot_Net_Assignment/Controllers/TeacherLeavesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Bhuma_Devi_Acharya_Dot_Net_Assignment.Data;
using Bhuma_Devi_Acharya_Dot_Net_Assignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace Bhuma_Devi_Acharya_Dot_Net_Assignment.Controllers
{
    [Authorize]

    public class TeacherLeavesController : Controller
    {
        private readonly Bhuma_Devi_Acharya_Dot_Net_AssignmentContext _context;

        public TeacherLeavesController(Bhuma_Devi_Acharya_Dot_Net_AssignmentContext context)
        {
            _context = context;
        }

        // GET: TeacherLeaves
        public async Task<IActionResult> Index()
        {
            return View(await _context.TeacherLeaves.ToListAsync());
        }

        // GET: TeacherLeaves/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TeacherLeaves/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeacherName,LeaveStartDate,NumberOfDays")] TeacherLeave teacherLeave)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacherLeave);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacherLeave);
        }

        // GET: TeacherLeaves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacherLeave = await _context.TeacherLeaves.FindAsync(id);
            if (teacherLeave == null)
            {
                return NotFound();
            }
            return View(teacherLeave);
        }

        // POST: TeacherLeaves/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TeacherName,LeaveStartDate,NumberOfDays")] TeacherLeave teacherLeave)
        {
            if (id != teacherLeave.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacherLeave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.TeacherLeaves.Any(e => e.Id == teacherLeave.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacherLeave);
        }

        // GET: TeacherLeaves/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacherLeave = await _context.TeacherLeaves
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacherLeave == null)
            {
                return NotFound();
            }

            return View(teacherLeave);
        }

        // POST: TeacherLeaves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacherLeave = await _context.TeacherLeaves.FindAsync(id);
            _context.TeacherLeaves.Remove(teacherLeave);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Bhuma_Devi_Acharya_Dot_Net_Assignment/Bhuma_Devi_Acharya_Dot_Net_Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bhuma_Devi_Acharya_Dot_Net_Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bhuma_Devi_Acharya_Dot_Net_Assignment.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bhuma_Devi_Acharya_Dot_Net_Assignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TeacherLeaves" asp-action="Index">
                                TeacherLeaves
                            </a>
                        </li>


                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Bhuma_Devi_Acharya_Dot_Net_Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>